### PR TITLE
Hide links in spoiler blocks

### PR DESCRIPTION
**Pull request by PeterBowman**
Resolves https://github.com/stjohann/DiscordWikiBot/issues/17. Tested on a sandbox Discord server.

### CODE REVIEW

**Comment by stjohann** [comment]
Great work, I’ll test it later this week. One issue I see: if there is a message `test [[link]] test ||[[link]]|| but in spoiler`, wouldn’t the output be with two links and not one due to how the `.Contains` check is done? I think two `if` blocks inside `str.length > 0` need to be swapped for it to work correctly.

**Comment by PeterBowman** [comment]
No, I considered that scenario: if two or more instances of the same link are present, there will be a single output marked as hidden whenever at least one such instance is found within a spoiler block. The first `if` clause will always see the "raw" link and add the spoiler decorator if applicable. The second one will never run twice over the same link (regardless of its visibility), thus there is no chance we end up with both `Add("<link>")` and `Add("||<link>||")`.

However, we can argue that in the above example it makes little sense to hide the output since the original (duplicate) link is visible anyway. I have submitted a fix and also simplified the code a bit.

**Comment by stjohann** [comment]
Suggested edit:
```diff
diff --git a/DiscordWikiBot/DiscordWikiBot.csproj b/DiscordWikiBot/DiscordWikiBot.csproj
index d9ec63d..29e9e38 100644
--- a/DiscordWikiBot/DiscordWikiBot.csproj
+++ b/DiscordWikiBot/DiscordWikiBot.csproj
@@ -6,7 +6,7 @@
 		<PackageLicenseFile>LICENCE.md</PackageLicenseFile>
 		<RepositoryUrl>https://github.com/stjohann/DiscordWikiBot</RepositoryUrl>
 		<RepositoryType>git</RepositoryType>
-		<Version>3.5.1</Version>
+		<Version>3.6.0</Version>
 		<Authors>stjn and others</Authors>
 		<Company />
 	</PropertyGroup>

```

**Review by stjohann — APPROVED** [review]
(Oops, sorry for the previous comment, blame VS Code.)

I checked the PR, the new version works exactly how I outlined this should work in #17. Nice job.

**Pull request merged**
